# ---------- BUILD STAGE ----------
FROM node:20.11.0 AS build

WORKDIR /app

# Copy package files & install dependencies
COPY package*.json ./
RUN npm install

# Copy all source code
COPY . .

# Prisma client generate
RUN npm run prisma:generate



# ---------- DEPLOYMENT STAGE ----------
FROM node:20.11.0 AS deployment

WORKDIR /app

# Copy package.json & install prod deps only
COPY package*.json ./
RUN npm install --omit=dev

# Copy all files from build stage
COPY --from=build /app .


# Run stage script
CMD ["npm", "run", "stage"]
